version: '3'

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jolivier/data/mariadb
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jolivier/data/wordpress
  
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - db:/var/lib/mysql 
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

  nginx:
    container_name: nginx
    networks:
      - inception
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

networks:
  inception:
    driver: bridge
