version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - ~/Documents/data/wp_db:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - ~/Documents/data/wp_files:/var/www/wordpress
    networks:
      - inception
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

  nginx:
    container_name: nginx
    volumes:
      - ~/Documents/data/wp_files:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

networks:
  inception:
    driver: bridge